GET http://ombelinepinoche-server.eddi.cloud:8443/api/location/1/spots/snowboard HTTP/1.1
Content-Type: application/json

{
}

GET http://0.0.0.0:8080/api/location/1/spots/snowboard HTTP/1.1
Content-Type: application/json

{
}
