GET http://0.0.0.0:8080/api/spots HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDc5OTkxMjcsImV4cCI6MTcwODAwMjcyNywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmZyIn0.OAHFU2MDm7Hb9nSQ-wN807czaCshdlr9aGJSjF3mscoCmZ8yf1vZR4bVcB03tq2QX-_6UtfwYIht_RxVG6tnXL3rEV7naEpZWdE41Knxjx7hJRHAxbLEglKxAeMGnX2R9H6h-ivwAHOGbIDy_0Koyl-nmKBbeJ2DnXd9OwIDZbnid3AX5C0mpZkPn5XSvDUDp1kaBKj_7D-fmAtcB47s8-cxjq_zLxMi65aC2pnrCRue8T-5ccQBZTo6JB8Y5R5GyiRA9Q5Zbfb9h63dwQHbOaeA3KSa4ngFmGX1oS-eZHMvqyW2Y5OQdNfd5S4sCIbqTnGnx_yvaAgUxXRvPaqy2A

{
}
