GET http://0.0.0.0:8080/api/location/paris/spots HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgwMDkxNzYsImV4cCI6MTcwODAxMjc3Niwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmZyIn0.OqXih5LEwYUjISs_A7bIJGRuM9LCqikk5bfR2ERijbxgD4iwvaVAc0NJkVIVDuPj0rVQ-xOXqPTVy0RP9LXRB3GMGb4e9oyUDCAKJl-x4IPEBRhPXzmsjspwC_H2o44I7T_l-Le5KEIlfXYNVX595cPQCISbEWABZ-xxnH1TsFs-cuA1RQ1b8Yj4f0ZxuFU56jOMmmv-NWSMqByixhM5TH1V_sB3I9vZzRwWb6GdVE9CJO71TrpqRZb3nVcNfvUGWu3X5xYtS5pEE5cc1QKA91u7PN_MCIM-nd2Au_YJ14T0wVh1_ZpDjW5lCvxs469MUOx63MRvwS5K6KPffAieRQ

{
}
