GET http://0.0.0.0:8080/api/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDg0MjA3ODQsImV4cCI6MTcwODQyNDM4NCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicmlkZXJAdXNlci5mciJ9.oo5Uegxv4jibVzVZPDSwa-sHRnnAIxHiPbvUrGXGvksGfI6ZNich14LcmN8J0Z5hzGKxI88goUA8BKYKED6HspUM-qnx1JxpuH7oJ4k2NM9CRgDU78Y_yQXwWjJsKvgAA1pbzA9ze7xChfTkJ5cA5c4WlxsVyWcpivGn7Nd7bTTdJTeg0ahBC3XXMhnJyr-ACFSWeIdUKoVM-ex8ylytukmhQs1J-y74hM2A32Dj8XbLKxXNMCVj7dqaAVeZYeHCR2HC0oC0Fg9FSSVe4s6xTtKy4Cu9oRYh-0k_e5q_vdRSmcGjEQSutsNLWoWwOack65GrGzopsqvDvNMrSycnug

{
}