GET http://0.0.0.0:8080/api/spot/isola-2000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgzNTAxNTYsImV4cCI6MTcwODM1Mzc1Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicmlkZXJAdXNlci5mciJ9.FClUJDSMWpKecEV9folhlPbdTwq8lyyCa6wcpJ18j-l8gAbyyaxnG4fdkrPM8WbsEwOYt1KAZGwhdxD-fGqLhAD6WXVjygqFhV1SX1OFdrx2W5DMtmzqcSl0k7uaRwGMwM6M48eoobSA5QCHk6O9RhNH7uImwEamx5iBOmoUlj4qGpQfp-kPXVJjhnUb1uChhbPOnIT_iKlsdBnGOIzHGCuTK0O45V1XlzHmYm5gAfkaLdI0xOnLFnrnk2CweADcbpzyyv8PuPleKOq708OTYu6Z5Up_jmtRAG9NE0jHBuFDBm3iqzbyxtDfEN-aSZXEenqVATBdftAq69vy5bgRTA

{
}