POST http://0.0.0.0:8080/api/spot/bercy/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDg0MjU5MDEsImV4cCI6MTcwODQyOTUwMSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicmlkZXJAdXNlci5mciJ9.q3eBL8TAHFgCQ2iGjyIAVv2NjPV9qCXMXUsRuVMjv3qbd1bxhtn7ioBzwjAenMfJ4YJIVhU7pN6BXKSb5wjJo-TAyYtsj1YwbYdgz0sXdbsxMnpa9GIuVL1pIbGLgY_1LdXXzKNV_2SGA-yJWYIMD3joSZUfE1IkY4ZQKpq4c0oHiRDgqaoYEWlk0KWb_4ypOe25hhxZUKli3VI9Kpk164w8LtAqb5q6DKyGjD96sITU6Gj8gyh3tkc0JHq_y-3afdft2iqtWcp_qKPgKguD3HpkKg4hEJjjfwGf7acAQhkLMwy4oAGPOYuKxm802q8Efs4EJJtSywUBTGZmjaUrvQ

{
    "content": "blabla",
    "rating": "4"
}
