PUT http://0.0.0.0:8080/api/secure/comment/28 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDg0MTcxMTksImV4cCI6MTcwODQyMDcxOSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicmlkZXJAdXNlci5mciJ9.Z32KZ6K2nUWIjxvTd97pNHMMzzRTLwiD9JetsiZOjSJ5dYAafkZHsaeGB8STQTq3GkP4tEe3iBFC-0D43ycrwWRksT4l4tUIIDE95pwj2x1pEgMw5KmK_QaxbGCW5_6M6nvDmpMpxi2FaK99NUZQmdcBfmJZlHe6H91sVE_ibUpUgRIVkUyVLt-iBucx7c6_TExufM30aNovpCrfVFt2EQkXjB-KWjpFvLzUmDsN6uZWgE--7mnkf25_larb2PbItrhRsytLu25lrANIKufJTwpK9ITUZAiXCxSXjHWOAYJUhU9vuS5jeOy7Jb3J4jSgcfVzsi5e6UlSC2wAgx3Eeg

{
    "content": "Pas foufou hein"
}
