PUT http://0.0.0.0:8080/api/secure/comment/9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgzNTQwMTksImV4cCI6MTcwODM1NzYxOSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicmlkZXJAdXNlci5mciJ9.pTD1tR88wCaUopcyBJLaRVB_LGqbnP0YrlIa-aAm2uz4EZ5Xi5a8QgNdF-z8E921SFaf4sCkijSLkFxvemV4e3Y5TnkCviY2gJbalW33Y0xq-PeUwymSqObQR1Q5wN8-zeF2qPRujI0gaaTyXpd355r2ur71yB0k4cRj4jBc4z_Rd25Vxxp9RiV8RmKpv_0KqZnKovjueIreqEHBsrjPjXjxmOtitOEKDjeY6ES7rRSC5lhDKsn_P_-0T77k9rmsqxesaJKSxD6_sWQjmMZxi-Khcj4cDuMGP2Ilpfy0zet1Uz69SF8P_IS-wPSWj35083rNh--j5PYLa_Tdp2_p2Q

{
    "content": "Là je dis oui!"
}
