DELETE http://0.0.0.0:8080/api/favorites/13 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDg1OTUxNDUsImV4cCI6MTcwODU5ODc0NSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicmlkZXJAdXNlci5mciJ9.nTY84SaSnYbGLSMocCCJ4IC64yrXG7HFcqKzAjM5QILrPjJWzq_yCDEX5FI7vwmTYLz0OG6lLHcxTPwXMRLzPiULER1CAFxSWU6saAqUEyc1t3kQpSoTmqlcAFf3h_ob-bndQKJ1bm2bKKRwv_u37UxBoQWcHRjYT3zMnixP7K8ODt_vhaYfwsW_yT7CLlJnWeloyTrXHNfkJAjEtmfLGdIuobILaRgj0DR5baxmW3vI80covQxbxPBNkz3g4jjsHsB1fs-fwpDbsQHxAjVnFLsAlXvlgebsDztbTcx5MouN6bemzhzWOPeBYRD7L7wjzJ2cBZQvEFlyXailS_cBYA

{
} 