DELETE http://0.0.0.0:8080/api/favorites/13 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDg1OTc4NTUsImV4cCI6MTcwODYwMTQ1NSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicmlkZXJAdXNlci5mciJ9.da8LuSaMhvERn5AxDpBOYtG7q0g6KAyVFvDJulk_cvtqHNHkA9pKw46gEL2e1L0qzw0H_cVXh8GIE92Vf9qyYyz0oO9KQH6jyifAjuBM2KRWYdIsAknaJd232aCd6AEjIhOai24rwxL3Wx8_QMdxnJ1VBh0Zn406hFkgFkPCfQ3Yx42GHyegsHNxUtoK4PqqKXrpwt0-6HPP6Ag8J8fyKA8pSVFLfxdvrMJUVMpnZeFWc3kr-LS_SfZ5Hjw-9_Wje42dLMIFZC2YEE0dWTnhFhMydWk0gjXGeAc99Tv_FD4nPBf4rmt1DDNBhsiNVcADcDJATAEmnNMBBndgGEkEtw

{
} 