GET http://0.0.0.0:8080/api/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgzNTU0MjIsImV4cCI6MTcwODM1OTAyMiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicmlkZXJAdXNlci5mciJ9.ku9Xv0CEazO5cWcAPsyVQH24vENUN1BxLyM9ciG-KoFSGUsncPNccDi_hxvETFIzjq7vqd22CiN1W8HXKryS2e0jyo1XY6t0YEQbrafEYhhh5OWytwlWtUZsp1rUOu08JjX4UmAe9PAbeFW3lvu0IzEUsKp6-M0c0AcU3GpJMTumIIXMsYKrdjpR2wGMQ3Qp58VnMKkalXckZvKPzIHUh3HNkjq3AJm2ujyXdmXnwqRbtMW764Odw4jbTQZ4TNBpo4oEQv28L-u12LIYwwnv7x7fpcyrEbrrNO7kMFkY2t2QnmU1eBblpoejDH0IL8kZuuCF7miCMitNrNh_5MVSUg

{
}