GET http://0.0.0.0:8080/api/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgwMzI1MTcsImV4cCI6MTcwODAzNjExNywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmZyIn0.pvbOIZix0MAFNebcz9FNsFVBXfjK2IU0wMEkwTJJudSwGP4UU_KCXEclLr_jmgTHbtUYenwPY_IhLPor9ENC7ie39lyEFawCat2UgYx0MAc9jU8Bushxs3W3leLI_4NS8_1GC4jVN8urnZEUU0clh7XmT9EZuWpqXRVb8QXlJEDkDCROKRq3eeRbeSavxQgvgk_mihhxTW1qE3_lZTQa01Q9W1mWXwoeIGNTYS2cxlBCYj_Y-M5aAFrnBP-ZEEZlWL8uvIJHyvGjU9u__OecdSoIx6t_X3xi8OLTS4qppHwj_QwAvL4Fm98MQzDtnTZ3Una1RMOk3yM9ntChJSqPvw

{
}