GET http://0.0.0.0:8080/api/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgwMDU1NDEsImV4cCI6MTcwODAwOTE0MSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmZyIn0.AE2WAdawkkSUR7Ci7h2jyYxpoagfYlomzxI0pjO-tlUzJ8MMMaL8FMXk5xH-pqxqyIBm-GCJcCjbBMwjNnC-HhzP6VCrhYEmi02Fjnt-pk-RE1F6tTixhJMAgKAARa-f09DGBfidI7rU8uoDfBKjyRsKE7fbko8Pw-m5m3z78E3p75YAGhsnMZ0AK5XiiibT0zLoFv-6Id__oOLGtj-70yuE2XW-Kw7KRD7C9AK9cCqMD45rtjYfVCh8GSmuHbfZ6LRLCG2nX7f8nArnTiwrc2_BRnP-KIHJ2uVyx_jIMm7DzYAnFDRARsxM5dmn1QvPjLiA5NA09qnkH-hcxk9vXA

{
}