POST http://0.0.0.0:8080/api/favorites/7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgwOTE4NTYsImV4cCI6MTcwODA5NTQ1Niwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmZyIn0.GJYgKwWZnJhCELdYwLDnEEJXcPAzvF70kB6hbvqYk78kYDar4I4muuMzy7sXghmFiWaiPNDcWyt3shVeKf8NL9O4NC3IkttBQWoZ1BNITw7HTbA98OwZ_RivMFDxwJPoHEKwlM3eVIA8XEyUvtcNdrS3xKBmPIT5WO65i1pgN6xm6MM-Zgxl1CPFOCXnMd9R6318HBoBxpWlVkN20CMW_bAmTt2EmIukD5akgE0SSttvbm8Sba_DXRPXVzGP_Y1BjJRRJeAp2tvz5TCiNBvR9PbrwgVaGflTb2ipOcI_cwfTr3XdKNToK8cCHcWO4zMneKeVpaC2_FkKfpik41nbyQ

{
}