POST http://0.0.0.0:8080/api/favorites/13 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgzMzA1OTAsImV4cCI6MTcwODMzNDE5MCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicmlkZXJAdXNlci5mciJ9.JSUOeM1SxIXTP29LpdNU7DECTf34uIb2VhtRwKxqDd4JVtJFFYAzu7zJ7keCBcRbo1K06k5uaNmI8cDC2zd10iTFHYm5GinxEcbSjfMgscLeg0bwuJWamv9B0Drtt4kkwBd2kaZGf-Jrz8Pejf2uKbqpoNyKm7gXYoRkk99fyogPjo_KlLMn441SzYL-ekUohJXlGuP0MNo3O5bYFDszoLnO63_L6F9ahtH6u_xVGQ6UUw6PxaFgn4feQNtskMMVAuld3YTLFKqgn-uc8EVgGfHs9Gah6OHhYyQ7Xw9jiOZnVGwBtZEqMY1g6a2sSv1XjgOd11Y0d1cvgeuPxE2Hyg 

{
}