POST http://0.0.0.0:8080/api/favorites/13 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDg1OTAxMTcsImV4cCI6MTcwODU5MzcxNywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicmlkZXJAdXNlci5mciJ9.tGGMaoUgZ-XKRl1rrx8fmnvzLjGYCS1GyLwhyl9h7HIwkYoJPMCm7sRbKNkkixPX6GObJMnG-MBuZcIE0zTRdko1F1e4zyJIlU5igsNyRdSbv4IGkIFd_SP9MIgs8I_ajVb576pnYFQtbrwVA0_6qgL_KJ_VtM4Vl42-RaYFvLo73lfwHq2gCeZ8TQA9XVW9st1l4dven4IkTHl6H0HhTcBE0H36EiU0ZJydxp1M3ScbHkRnlrz7Pem-OZ4BqodjQ38MAK3JJGFyBXjV5Rjlk51YvOkgwbeNOWS7-iiLojal0n4Vd5oOQzp3Da8tYmKNhqdYSVePsKmsV48Q7n7u3Q

{
}