GET http://0.0.0.0:8080/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgwMzI0NTIsImV4cCI6MTcwODAzNjA1Miwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicmlkZXJAdXNlci5mciJ9.rPQSvsBf4iElrf_8hxlJLOpC93JoWL9w3br2a5OnvViYKaFqpjTsOsZ3lLx6gthKuV2gdbUzeu1fgr8idtJ8TSRO27gxMr1I3YGrcG7LqXm8Dsx6JDbE1wPfHxf2_YYIM3D1v1Jz4vpwuPD3Ck-5Nn6BES9f5hDrRRrVmyi5CSn-cv0VV9Zm2zi2zP9kpqSNCJa9IJ5d_tQDvnY088MeA41ycrYNehDpVkb0zw0aLFylX-mjya0jZJ2I299OwRrKBzpkM4LZLuCNxO24cg00oHX3crsnujwbcqUIXSWUAWkVmMMrbtbtU4hYQCgcBbZrZEBgdk9wUltKmvUef8VTgQ

{
}
