GET http://0.0.0.0:8080/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDkxMTQ5MDAsImV4cCI6MTcwOTExODUwMCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmZyIn0.KbMDnmyblY6OflfQ1PqtRFdA-NZnNQvYHM8bY8NqgV9Y6qzu-gPosojsqQydzC1poGaWeGWYB2qD5eRAGgWe_VHHEofX7cjMz-DgLVNWInK3i7tNF2HLGRRqkPd4b_wlFTbiuu6WHqv3v-YJuUp34oqWpYOqmGRlDNBEUJ0UWUBXiSnjwFH5VfzQprGlEZyNZc3aGAaI4XUprixqgOb5-Xd48YHDRz8BxDNf8j0uBuOCmfpLDrQsgJAlXzdunaYTMLAX-xWdzv1iu8AcykYAum_8-bfej-eusI2Kep6VuFe1KMreOPkvRP6vuYSOSiOQL3kO_VQAF9B6zMcEwIrV8w

{
}
