GET http://0.0.0.0:8080/api/user/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgwNzU0MTAsImV4cCI6MTcwODA3OTAxMCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmZyIn0.quGntYQQnvpGeb2Cynx6KbhvLl4L0ncRkrwSo_1UCJoRyD2IUcpVO753S1OMfXtNb7wODKiwBybS4mB51LOjYWIbSMrTPVp4M0andYSFwil-cR0FFXznlHElhtHCf6W2yp0JEavN9jSnOAACnX1dW0eOUWj4xvO7P9Wb95YZjY7wYsUXyxGUdVHmq07jh_o8GH9GYZKulq7CFk1JHPHjlPfLTjeCMWeqp54oRphOyNS0307bYCpimW4EwC0t1g9F4PMMluT00dJe-yzeazHXpSDHyeSkUfsCfrvb1F9KYdCsi8UHH6dw-FlHNM4Mh8bXzWy5Qw7oDnXwPndAB-b5Eg

{
}
