POST http://localhost/Symfony/BTSback/projet-04-balance-ton-spot-back/ HTTP/1.1
Content-Type: application/json

{
    "name": "DouchePark",
    "description" : "Le terrain de jeu pour tous les douchebags passionnés de skate!",
    "picture" : "http://douchebag.com",
    "address" : "29 boulevard foch",
    "location_id" :  5
}

