name: Build and deploy PHP app to AWS - balancetonspot-api

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/BalanceTonSpot-Back
          git pull
          composer install --no-dev --optimize-autoloader
          php bin/console assets:install --symlink --relative public
          php bin/console doctrine:migrations:migrate
          sudo systemctl restart apache2